image: quay.io/fenicsproject/dev-env:latest

pipelines:
  default:
    - step:
        script:
          - pip3 install git+https://bitbucket.org/fenics-project/fiat.git@master
          - pip3 install git+https://bitbucket.org/fenics-project/ufl.git@master
          - pip3 install git+https://bitbucket.org/fenics-project/dijitso.git@master
          - pip3 install git+https://bitbucket.org/fenics-project/ffc.git@master
          - mkdir -p build
          - cd build
          - cmake -DCMAKE_BUILD_TYPE=Developer ..
          - make -j2
          - make install
          - cd ../python
          - pip3 install .
          - cd demo
          - python3 ./generate-demo-files.py
          - cd documented/poisson
          - python3 ./demo_poisson.py
