image: quay.io/fenicsproject/dev-env:latest

pipelines:
  default:
    - step:
        script:
          - pip3 install pytest --upgrade
          - apt-get -y update && apt-get -y install python3-tk
          - pip3 install git+https://bitbucket.org/fenics-project/fiat.git@master
          - pip3 install git+https://bitbucket.org/fenics-project/ufl.git@master
          - pip3 install git+https://bitbucket.org/fenics-project/dijitso.git@master
          - pip3 install git+https://bitbucket.org/fenics-project/ffc.git@master

          - mkdir -p build
          - cd build
          - cmake -DCMAKE_BUILD_TYPE=Developer ..
          - make -j2
          - make install

          - cd ../python
          - pip3 install .

          - cd test
          - python3 -m pytest unit/mesh
          #- python3 -m pytest unit/io

          - cd ../demo
          - python3 ./generate-demo-files.py
          - cd documented/poisson
          - export DOLFIN_NOPLOT=1
          - python3 ./demo_poisson.py
          - mpirun -np 3 python3 ./demo_poisson.py
          - cd ../stokes-taylor-hood
          - python3 ./demo_stokes-taylor-hood.py
          - cd ../../undocumented/elasticity
          - python3 demo_elasticity.py
