image: quay.io/fenicsproject/dev-env:latest

pipelines:
  default:
    - step:
        script:
          - pip3 install git+https://bitbucket.org/fenics-project/fiat.git@master
          - pip3 install git+https://bitbucket.org/fenics-project/ufl.git@master
          - pip3 install git+https://bitbucket.org/fenics-project/dijitso.git@master
          - pip3 install git+https://bitbucket.org/fenics-project/ffc.git@master
          - mkdir -p build
          - cd build
          - cmake .. -DCMAKE_BUILD_TYPE=Debug -DDOLFIN_ENABLE_TESTING=OFF
          - make
          - make install
          - source /usr/local/share/dolfin/dolfin.conf

